version: "3"
services:
  db-publications:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: creative-hub-publications
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  microservice-publications:
    build: .
    image: ghcr.io/creative-hub-taass/microservice-publications:latest
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db-publications
      - DB_NAME=creative-hub-publications
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - JAVA_ARGS=$JAVA_ARGS
    depends_on:
      - db-publications
