apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: microservice-publications
  name: microservice-publications
spec:
  ports:
    - name: api
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: microservice-publications
